### ISSUE TITLE
Test failure: `getBody: > should pass request error for bar url`

### ISSUE THREAD

**Issue by JamesCropcho** [plotly/image-exporter#49]
Greetings, all.

Locally I get this test failure:

```
  not ok Cannot read property 'code' of null
    stack: |
      getBody (test/unit/runner_test.js:96:18)
      Request.request.get [as _callback] (src/app/runner/get-body.js:47:7)
      Request.self.callback (node_modules/request/request.js:186:22)
      Request.<anonymous> (node_modules/request/request.js:1163:10)
      IncomingMessage.<anonymous> (node_modules/request/request.js:1085:12)
    at:
      line: 96
      column: 18
      file: test/unit/runner_test.js
      function: getBody
    type: TypeError
    test: should pass request error for bar url
    source: |
      t.equal(err.code, 'ENOTFOUND', 'error')
```

And while `code` is indeed null, `body` is
> `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head><meta http-equiv="refresh" content="0;url=http://searchassist.verizon.com/main?ParticipantID=euekiz39ksg8nwp7iqj2fp5wzfwi5q76&FailedURI=http%3A%2F%2Fdummy.url%2F&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us"/><script type="text/javascript">url="http://searchassist.verizon.com/main?ParticipantID=euekiz39ksg8nwp7iqj2fp5wzfwi5q76&FailedURI=http%3A%2F%2Fdummy.url%2F&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us";if(top.location!=location){var w=window,d=document,e=d.documentElement,b=d.body,x=w.innerWidth||e.clientWidth||b.clientWidth,y=w.innerHeight||e.clientHeight||b.clientHeight;url+="&w="+x+"&h="+y;}window.location.replace(url);</script></head><body></body></html>`

The ISP I'm using responds with this page when the URI has a nonexistent domain. However, `body` is only a string literal and so I see no quick fix.

I am happy to fix this (probably by modifying `getBody()`), and just as happy to ignore it. Direct me as you see fit.

I believe you would at least want to be aware of this. Not limited to, that if after I "pipify" this tool, that `getBody()` will be called on laptops and/or servers outside with a variety of ISP behavior.

Hoping to Help,
James

**Comment by etpinard** [comment]
I haven't seen this thing fail in a long time.

@JamesCropcho ok to close this?

**Comment by JamesCropcho** [comment]
@etpinard I don't believe (?) I see this particular failure anymore, although I do encounter another(s) nondeterministic failure with some regularity.

**Comment by etpinard** [comment]
Ok. Closing and merging with https://github.com/plotly/image-exporter/issues/61
