### ISSUE TITLE
List supported output formats via help 

### ISSUE THREAD

**Issue by cpsievert** [plotly/image-exporter#79]
Would be nice to be able to quickly see supported output formats, perhaps via `plotly-graph-exporter --help`?

https://github.com/plotly/image-exporter/blob/433d619414c92f0c612d399cb72ca9a7b22bc5a0/bin/args.js#L141-L142

**Comment by etpinard** [comment]
That's under `--format`:

![image](https://user-images.githubusercontent.com/6675409/38942457-ccc9366e-42fc-11e8-9410-ad524daea8b8.png)

**Comment by cpsievert** [comment]
Ahh, sorry! Should all these formats work (in theory) for gl trace types as well?

**Comment by etpinard** [comment]
> Ahh, sorry! Should all these formats work (in theory) for gl trace types as well?

Yes. They work. Not just in _theory_.
